#!/usr/bin/perl
# vim: ts=3

use strict;

my $file = shift @ARGV;

if (!-r $file) {
	my $tfile = `pwd`;
	chomp $tfile;
	if ($tfile =~ /\/([^\/]+)-analysis/) {
		$file = "../$1.tiff";
	}
}

my @contents = <>;

# @PRELEADER_ROW:		749px
#@IMAGE_WIDTH:		4096px
#@LEADER_ROW:		2484px

my $width = 0;
my $height = 0;
my $offset = 0;
my $endpoint = 0;
for (my $i=0; $i<@contents; $i++) {
	if ($contents[$i] =~ /^\@PRELEADER_ROW:\s*(\d+)(px)?/) {
		$offset = $1;
	}
	if ($contents[$i] =~ /^\@LEADER_ROW:\s*(\d+)(px)?/) {
		$endpoint = $1;
	}
	if ($contents[$i] =~ /^\@IMAGE_WIDTH:\s*(\d+)(px)?/) {
		$width = $1;
	}
	if ($contents[$i] =~ /^\@\@BEGIN:\s*TEARS/) {
		last;
	}
}

$height  = $endpoint - $offset + 1;


die "Width is zero" if $width == 0;
die "Height is zero" if $height == 0;
die "Too wide" if $width > 5000;
die "Too high" if $height > 5000;

my $command = "convert $file";
$command .= " -crop ${width}x$height+0+$offset";
$command .= " -flip";
$command .= " -resize 1024";
$command .= " leader.jpg";
print "$command\n";
`$command`;



