

SRC = "../../"



all:
	cp $(SRC)/extractBadHoles	.
	cp $(SRC)/extractLeader		.
	cp $(SRC)/extractPreleader	.
	cp $(SRC)/extractTears		.
	cp $(SRC)/generateReport	.
	cp $(SRC)/makeanalysis		.
	cp $(SRC)/makebicolor		.
	cp $(SRC)/makechannels		.
	cp $(SRC)/makedriftfile		.
	cp $(SRC)/Makefile-analysis	.
	cp $(SRC)/Makefile		Makefile-directory
	cp $(SRC)/makehistograms	.
	cp $(SRC)/makejpg		.
	cp $(SRC)/makesmalljpg		.
	cp $(SRC)/makethumbnail		.


